
export const APP_LOADED = 'APP_LOADED'
export const REDIRECT = 'REDIRECT'

// Apollo client GQL
export const EXPLORATION_CREATED = 'EXPLORATION_CREATED'
export const ACCESS_CODE_AUTHORZED = 'ACCESS_CODE_AUTHORZED'
export const BEGIN_EXPLORATION = 'BEGIN_EXPLORATION'


export const AUTHORIZE_ACCESS_CODE = 'AUTHORIZE_ACCESS_CODE'
export const AUTHORIZE_ACCESS_CODE_PENDING = 'AUTHORIZE_ACCESS_CODE_PENDING'
export const AUTHORIZE_ACCESS_CODE_FULFILLED = 'AUTHORIZE_ACCESS_CODE_FULFILLED'
export const AUTHORIZE_ACCESS_CODE_REJECTED = 'AUTHORIZE_ACCESS_CODE_REJECTED'


export const EXPLORATION_PAGE_TERMS_SELECTION = 'EXPLORATION_PAGE_TERMS_SELECTION'
export const EXPLORATION_PAGE_UNLOAD = 'EXPLORATION_PAGE_UNLOAD'
export const EXPLORATION_PAGE_TERMS_COMPLETE = 'EXPLORATION_PAGE_TERMS_COMPLETE'


export const FORM_COMMIT = 'FORM_COMMIT'
export const FORM_SUBMIT_API = 'FORM_SUBMIT_API'
export const FORM_SUBMIT_API_PENDING = 'FORM_SUBMIT_API_PENDING'
export const FORM_SUBMIT_API_FULFILLED = 'FORM_SUBMIT_API_FULFILLED'
export const FORM_SUBMIT_API_REJECTED = 'FORM_SUBMIT_API_REJECTED'


export const EXPLORATION_CREATE_ANIMATE = 'EXPLORATION_CREATE_ANIMATE'
export const EXPLORATION_CREATE_ANIMATE_COMPLETE = 'EXPLORATION_CREATE_ANIMATE_COMPLETE'
export const EXPLORATION_CREATE = 'EXPLORATION_CREATE'
export const EXPLORATION_CREATE_PENDING = 'EXPLORATION_CREATE_PENDING'
export const EXPLORATION_CREATE_FULFILLED = 'EXPLORATION_CREATE_FULFILLED'
export const EXPLORATION_CREATE_REJECTED = 'EXPLORATION_CREATE_REJECTED'