
export const APP_LOADED = 'APP_LOADED'
export const REDIRECT = 'REDIRECT'

export const EXPLORATION_PAGE_TERMS_SELECTION = 'EXPLORATION_PAGE_TERMS_SELECTION'
export const EXPLORATION_PAGE_UNLOAD = 'EXPLORATION_PAGE_UNLOAD'

export const EXPLORATION_PAGE_TERMS_COMPLETE = 'EXPLORATION_PAGE_TERMS_COMPLETE'


export const FORM_COMMIT = 'FORM_COMMIT'
export const FORM_SUBMIT_API = 'FORM_SUBMIT_API'
export const FORM_SUBMIT_API_PENDING = 'FORM_SUBMIT_API_PENDING'
export const FORM_SUBMIT_API_FULFILLED = 'FORM_SUBMIT_API_FULFILLED'
export const FORM_SUBMIT_API_REJECTED = 'FORM_SUBMIT_API_REJECTED'


export const DOMAIN_FETCH_ANIMATE = 'DOMAIN_FETCH_ANIMATE'
export const DOMAIN_FETCH_ANIMATE_COMPLETE = 'DOMAIN_FETCH_ANIMATE_COMPLETE'
export const DOMAIN_FETCH = 'DOMAIN_FETCH'
export const DOMAIN_FETCH_PENDING = 'DOMAIN_FETCH_PENDING'
export const DOMAIN_FETCH_FULFILLED = 'DOMAIN_FETCH_FULFILLED'
export const DOMAIN_FETCH_REJECTED = 'DOMAIN_FETCH_REJECTED'