// Page routing functions to turn off and on ther forms activations

export const EXPLORATION_PAGE_TERMS_SELECTION = 'EXPLORATION_PAGE_TERMS_SELECTION'
export const EXPLORATION_PAGE_UNLOAD = 'EXPLORATION_PAGE_UNLOAD'
export const EXPLORATION_PAGE_TERMS_COMPLETE = 'EXPLORATION_PAGE_TERMS_COMPLETE'